name: Abaplint

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
     current: ${{steps.getbranchname.outputs.current}}
    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
      - name: Get Current Branch name
        id: getbranchname
        run: |
          {
            echo 'current<<EOF'
            echo $(git branch --show-current)
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get changed files
        id: changes
        run: |
          {
            echo 'all<<EOF'
            echo $(git diff --name-only ${{steps.getbranchname.outputs.current}}..origin/main --)
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: abaplint
        uses: valeriast/actions-abaplint@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ steps.changes.outputs.all }}
