name: Abaplint

on: [push]

jobs:       
  workflow:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
     changedfiles: ${{steps.changes.outputs.changedfiles}}
     current: ${{steps.getbranchname.outputs.current}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get Current Branch name
        id: getbranchname
        run: |
          {
            echo 'current<<EOF'
            echo $(git branch --show-current)
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get changed files
        id: changes
        run: |
          {
            echo 'changedfiles<<EOF'
            echo $(git diff --name-only ${{steps.getbranchname.outputs.current}}..origin/main --)
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Fetch check run ids
        id: fetchcheckrun
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/actions/runs/{run_id}/jobs
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: abaplint
        uses: valeriast/actions-abaplint-v2@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ steps.changes.outputs.changedfiles }}
          GITHUB_CHECK_RUN_ID: ${{steps.fetchcheckrun.outputs.data}}
        
