name: Abaplint

on: [pull_request]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changes
        run: |
          {
            echo 'all<<EOF'
            echo $(git log --name-only --pretty=format: --stat origin/main..${{ github.head_ref }})
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: abaplint
        uses: valeriast/actions-abaplint@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ steps.changes.outputs.all }}
