name: Abaplint

on: [pull_request, push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch name
        id: branch_name
        run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Get changed files
        id: changes
        run: |
          git fetch origin main:refs/remotes/origin/main
          {
            echo 'all<<EOF'
            echo $(git log --name-only --pretty=format: --stat main..$current_branch)
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: abaplint
        uses: valeriast/actions-abaplint@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ steps.changes.outputs.all }}
