name: CI

on: [push]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "all=$(git diff --name-only HEAD^)" >> "$GITHUB_OUTPUT"
      - name: abaplint
        uses: valeriast/actions-abaplint@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ needs.changedfiles.outputs.all }}
