name: CI

on: [push]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "all=$(git diff --name-only HEAD^)" >> "$GITHUB_OUTPUT"

  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    # if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: echo changed files
        env:
          ALL1: ${{needs.changedfiles.outputs.all}}
        run: echo "$ALL1"
