name: CI

on: [pull_request]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> "$GITHUB_OUTPUT"
      - name: echo changed files
        env:
          ALL1: ${{steps.changes.outputs.all}}
        run: echo "$ALL1"
