name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        run: >
           echo CHANGED_FILES=$(echo $(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}")) >> $GITHUB_ENV
 
      - name: List all changed files
        run: |
          for file in $CHANGED_FILES; do
            echo "$file was changed"
          done
